" File: vimrc
" Project: scyn-conf/conf/vim
" Brief: Vim main configuration file
" Author: Scyn - Remi Chaintron <remi.chaintron@gmail.com>
"

source ~/.vim/compatibility.vim
source ~/.vim/general.vim
source ~/.vim/autocommands.vim
source ~/.vim/buffers.vim
source ~/.vim/display.vim
source ~/.vim/editing.vim
source ~/.vim/folding.vim
source ~/.vim/goto.vim
source ~/.vim/indentation.vim
source ~/.vim/langdep.vim
source ~/.vim/plugins.vim
source ~/.vim/search.vim
source ~/.vim/statusline.vim
source ~/.vim/sudo.vim
source ~/.vim/syntax.vim
source ~/.vim/tabs.vim
source ~/.vim/tags.vim
source ~/.vim/tiger.vim
source ~/.vim/textwidth.vim
source ~/.vim/windows.vim
source ~/.vim/yank.vim

