# File: zshrc
# Brief: Zsh configuration file
# Version: 0.1
# Author: Scyn - Remi Chaintron <remi.chaintron@gmail.com>

CONF_DIR="$HOME/conf"
ZSH_CONF_DIR="$CONF_DIR/zsh"

pushd "$ZSH_CONF_DIR/zsh" >&-

# Handle known hosts
case $HOST in
	lisp|caml|ruby|ada|php|asp|sh|java|apl|pascal)
		source ./acu.zsh
		source ./epita.zsh
	;;
	A.Bettik)
		source ./a.bettik.zsh
	;;
	Consul)
		source ./consul.zsh
	;;
	gate-ssh)
		echo -e "\033[31mLogged in gate-ssh, forwarding to freebsd\033[0m"
		ssh freebsd
		echo -e "\033[31mLogged out freebsd, disconnecting from gate-ssh\033[0m"
		exit
	;;
	*)
		if /usr/school/bin/ns_who >&-; then
			source ./epita.zsh
		fi
	;;
esac

source zshrc.zsh
popd >&-

## Keep an empty line!

